[webservers]
iu-devops-vm ansible_host=213.165.209.206 ansible_user=ubuntu

[group_name]
iu-devops-vm ansible_host=213.165.209.206 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519_y_cloud

[group_name:vars]
ansible_python_interpreter=/usr/bin/python3
