{{- if .Values.k8sSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info-chart.k8sSecretName" . }}
  labels:
    {{- include "devops-info-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.k8sSecret.data.username | quote }}
  password: {{ .Values.k8sSecret.data.password | quote }}
{{- end }}