replicaCount: 5

image:
  tag: a6eb67992f8c0f5127dc9e09862621f662597c9e

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: LoadBalancer
  nodePort: null

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 3

k8sSecret:
  data:
    username: "prod-user-placeholder"
    password: "prod-password-placeholder"

vault:
  enabled: true
  role: "devops-info-role"
  secretPath: "secret/data/devops-info/config"
  injectedFileName: "vault-config"

config:
  environment: prod

envConfig:
  APP_ENV: prod
  LOG_LEVEL: INFO
  FEATURE_VISITS_COUNTER: "true"
  VISITS_FILE: /data/visits

persistence:
  enabled: true
  size: 500Mi
  storageClass: ""
  mountPath: /data

rollout:
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
